name: Isostichopus badionotus
favicon: null
layout_spectrum: 0.57674
typography_spectrum: 0.6381
title: Isostichopus badionotus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77178700-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d7cde5'
    - '#3855a5'
    - '#6eb5df'
    - '#777bbb'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
