name: Isostichopus badionotus
favicon: null
layout_spectrum: 0.35998
typography_spectrum: 0.8332210339140147
title: Isostichopus badionotus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: FS-1989-23
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#304035'
    - '#7b886c'
    - '#a4ae8c'
    - '#dae2bd'
    - '#fbfee9'
  brandStrength: 0.5
  lightness: 0.44977094512432814
  saturation: 0.5515685263089836
  rhythmicContrast: 0.7405921956524253
purpose: []
