name: Isostichopus badionotus
favicon: null
layout_spectrum: 0.62366
typography_spectrum: 0.8332210339140147
title: Isostichopus badionotus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76810938-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#312414'
    - '#ffffff'
    - '#8e623d'
    - '#b3ae86'
    - '#f4c695'
  brandStrength: 0.5
  lightness: 0.44977094512432814
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
