name: Isostichopus badionotus
favicon: null
layout_spectrum: 0.90364
typography_spectrum: 0.8332210339140147
title: Isostichopus badionotus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7991b5'
    - '#b9c2d1'
    - '#195055'
    - '#050507'
    - '#ffee79'
  brandStrength: 0.8480997197329998
  lightness: 0.44977094512432814
  saturation: 0.5515685263089836
  rhythmicContrast: 0.7405921956524253
purpose: []
