name: Isostichopus badionotus
favicon: null
layout_spectrum: 0.62728
typography_spectrum: 0.6381
title: Isostichopus badionotus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77178700-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5d7486'
    - '#a29c8e'
    - '#4d414d'
    - '#cbc1b8'
    - '#f7d66d'
  brandStrength: 0.5625
  lightness: 0.44977094512432814
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
