name: Isostichopus badionotus
favicon: null
layout_spectrum: 0.57674
typography_spectrum: 0.6381
title: Isostichopus badionotus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77178700-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ccb5a7'
    - '#b08f7c'
    - '#915b43'
    - '#88301c'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
