name: Isostichopus badionotus
favicon: null
layout_spectrum: 0.5115851941518486
typography_spectrum: 0.8332210339140147
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8480997197329998
  lightness: 0.44977094512432814
  saturation: 0.5515685263089836
  rhythmicContrast: 0.7405921956524253
purpose: []
