name: Isostichopus badionotus
favicon: null
layout_spectrum: 0.17751
typography_spectrum: 0.8332210339140147
title: Isostichopus badionotus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76810938-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafaf0'
    - '#bec9b9'
    - '#130000'
    - '#e99d51'
    - '#443927'
  brandStrength: 0.5
  lightness: 0.44977094512432814
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
